---
title: "Evaluate elections"
date: '`r Sys.Date()`'
output: 
  pdf_document: 
    toc: yes
    number_sections: yes
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stanpop)
paths_to_pop_objects <- "[pop_paths]"
pops <- stanpop:::rmd_read_pops(paths_to_pop_objects)

parameter_path <- "[parameter_path]"
param_default <- list("full_period" = TRUE, 
                      "last_election_period" = TRUE,
                      "last_latent_state_summary" = FALSE,
                      "election_periods" = FALSE,
                      "election_campaigns" = FALSE,
                      "sigma" = TRUE,
                      "plot_parameters" = NULL,
                      "summary_parameters" = NULL,
                      "diagnostics_table" = TRUE,
                      "model_information" = TRUE)
params <- stanpop:::rmd_read_params(parameter_path)
params <- stanpop:::rmd_parse_parameters(params, param_default)

checkmate::assert_list(pops, len = 1)

parties <- stanpop:::rmd_pops_unique_parties(pops)

mi <- stanpop:::rmd_model_settings_with_unique(pops)
mi <- mi[order(mi$model_setting),]
mi$model <- mi$i

mu <- stanpop:::rmd_model_settings_unique(pops)

```

\pagebreak

# Evaluation at Elections

```{r,results='asis', echo=FALSE}

if(params$model_information){
  cat("\n## Model settings\n")
  knitr::kable(mu, 
              caption = "Model settings", 
              row.names = FALSE)
}
```


```{r, results='asis', echo=FALSE, fig.height=3, fig.width=4,fig.show="hold", out.width="50%"}
if(params$diagnostics_table){
    
  cat("\n## Model calibration \n")
  
  per <- stanpop:::rmd_last_known_state_percentile(pops)
  per$ndraws <- NULL
  nmi <- stanpop:::rmd_model_settings_with_unique(pops)
  per <- merge(per, nmi[, c("sha", "model_setting", "polls_time_to")])
  model_settings <- sort(unique(per$model_setting))
  
  results <- data.frame(model_settings = model_settings,
                        extreme_percentiles = rep(0, length(model_settings)))
  
  for(i in seq_along(model_settings)){
    per_mod <- per[per$model_setting == model_settings[i], ]
    per_mod$sha <- per_mod$date <- per_mod$model_setting <- per_mod$polls_time_to <- NULL
    perc <- unlist(per_mod)
    perc <- data.frame(percentile = perc[!is.na(perc)])
    plt <- ggplot2::ggplot(perc, ggplot2::aes(y=, x=percentile)) + 
      ggplot2::geom_histogram() + 
      ggplot2::theme_bw() + 
      ggplot2::ggtitle(paste("Model setting", model_settings[i], collapse = " "))
    suppressWarnings(suppressMessages(print(plt)))
    results$model_settings[i] <- model_settings[i]
    results$extreme_percentiles[i] <- 
      mean(perc$percentile < 0.005 | perc$percentile > 0.995)
  }
  
  print(knitr::kable(results, 
                     digits = 3, 
                     caption = paste0("Percentiles Summary"), 
                     row.names = FALSE))
  
}
```


```{r, results='asis', echo=FALSE}
if(params$diagnostics_table){
    
  cat("\n## Model performance\n")
  res <- rmse_res <- stanpop:::rmd_last_known_state_evaluation_by_model_setting(pops, type = "rmse")
#  elpd_res <- stanpop:::rmd_last_known_state_evaluation_by_model_setting(pops, type = "elpd")
#  res <- cbind(rmse_res[,c("model_setting", "rmse")], elpd_res[,c("elpd", "n")])
  print(knitr::kable(res, 
                     digits = 3, 
                     caption = paste0("Model setting performance"), 
                     row.names = FALSE))
}
```

```{r, results='asis', echo=FALSE}
if(params$diagnostics_table){
    
  cat("\n## RMSE\n")
  nmi <- stanpop:::rmd_model_settings_with_unique(pops)
  per <- stanpop:::rmd_last_known_state_evaluation(pops, type = "rmse")
  per <- merge(per, nmi[, c("sha", "model_setting", "polls_time_to")])
  per <- per[order(per$polls_time_to, per$model_setting),]
  

  party <- "M" 
  pnm <- make.names(stanpop:::rmd_get_other_parties_in_known_state(party))
  per_swe <- per[!is.na(per[[party]]), c("polls_time_to", "model_setting", "sha", "ndraws", pnm[pnm%in%colnames(per)])]
  if(nrow(per_swe) > 0){
    print(knitr::kable(per_swe, 
                       digits = 3, 
                       caption = paste0("RMSE Sweden"), 
                       row.names = FALSE))
  }

}
```



```{r, results='asis', echo=FALSE}
if(params$diagnostics_table){
    
  cat("\n## Percentiles\n")
  nmi <- stanpop:::rmd_model_settings_with_unique(pops)
  per <- stanpop:::rmd_last_known_state_percentile(pops)
  per <- merge(per, nmi[, c("sha", "model_setting", "polls_time_to")])
  per <- per[order(per$polls_time_to, per$model_setting),]
  

  # Sweden
  party <- "M" 
  pnm <- make.names(stanpop:::rmd_get_other_parties_in_known_state(party))
  per_swe <- per[!is.na(per[[party]]), c("polls_time_to", "model_setting", "sha", "ndraws", pnm[pnm%in%colnames(per)])]
  if(nrow(per_swe) > 0){
    print(knitr::kable(per_swe, 
                       digits = 3, 
                       caption = paste0("Percentiles Sweden"), 
                       row.names = FALSE))
  }

}
```


```{r, echo=FALSE, results='asis', fig.height=3, fig.width=9}
if(params$last_election_period){
  cat("## Election predictions \n")
  
  for(i in seq_along(parties)){
    party <- parties[i]
    cat("\n### ", party, "\n")
    for(j in 1:nrow(mi)){
      cat("\n")
      pop <- pops[[mi$i[j]]]
      if(!(party %in% pop$y)) next
      
      ks <- stanpop:::rmd_get_known_states(party)
        
      plt <- plot(pop, 
                  party, 
                  shift_latent_days = 6L,
                  from = unname(pop$model_time_range["to"] - 150),
                  to = unname(pop$model_time_range["to"]),
                  latent_state_colour = stanpop:::party_color(party)) + 
        geom_known_state(ks, party) + 
        ggplot2::theme_bw()
      tit <- paste0("From ", mi$polls_time_to[j], ": Setting ", mi$model_setting[j], " (model ", mi$i[j], ") ")
      plt <- plt + ggplot2::ggtitle(tit)
      suppressWarnings(print(plt))
      cat("\n")
    }
    cat("\n")
  }
}

```

```{r, results='asis', echo=FALSE}
if(params$last_latent_state_summary){
  cat("## Last latent state summary \n")
}
```
```{r, echo=FALSE}
if(params$last_latent_state_summary){
  print(pops[[1]]$y)
  for(j in seq_along(pops)){
    last_params <- paste0("x_pred[", pops[[j]]$stan_data$stan_data$T, ",", 1:pop$stan_data$stan_data$P, "]")
    rstan:::print.stanfit(pops[[j]]$stan_fit, pars = last_params, digits_summary = 3)
  }
}
```

```{r, echo=FALSE, results='asis', fig.height=4, fig.width=4,fig.show="hold", out.width="50%"}

if(params$sigma){
  cat("## Sigma \n")
  
  for(j in seq_along(pops)){
    pn <- parameter_names(pops[[j]])
    cat("\n")
    no_sigma_x <- sum(grepl(pn, pattern = "sigma_x\\["))
    if(no_sigma_x > 1) plnsx <- pops[[j]]$y else plnsx <- "sigma_x"
    if(no_sigma_x > 0){
      plt <- plot_parameters_areas(pops[[j]], 
                                   paste0("sigma_x[", 1:no_sigma_x, "]"), 
                                   plnsx, 
                                   area_method = "equal height")
      tit <- "sigma_x"
      if(length(pops) > 1) tit <- paste0(tit, ": Model ",j)
      plt <- plt + ggplot2::ggtitle(tit)
      suppressWarnings(print(plt))
    }
    cat("\n")
  }
}

```

```{r, echo=FALSE, results='asis', fig.height=4, fig.width=4,fig.show="hold", out.width="50%"}

if(params$sigma){
  for(j in seq_along(pops)){
    pn <- parameter_names(pops[[j]])
    cat("\n")
    no_sigma_xc <- sum(grepl(pn, pattern = "sigma_xc\\["))
    if(no_sigma_xc > 1) plnsx <- pops[[j]]$y else plnsx <- "sigma_xc"
    if(no_sigma_xc > 0){
      plt <- plot_parameters_areas(pops[[j]], 
                                   paste0("sigma_xc[", 1:no_sigma_xc, "]"), 
                                   plnsx, 
                                   area_method = "equal height")
      tit <- "sigma_xc"
      if(length(pops) > 1) tit <- paste0(tit, ": Model ",j)
      plt <- plt + ggplot2::ggtitle(tit)
      suppressWarnings(print(plt))
    }
    cat("\n")
  }
}

```

```{r, echo=FALSE, results='asis', fig.height=4, fig.width=4,fig.show="hold", out.width="50%"}

if(params$sigma){
  for(j in seq_along(pops)){
    pn <- parameter_names(pops[[j]])
    cat("\n")
    no_sigma_ep <- sum(grepl(pn, pattern = "sigma_ep\\["))
    if(no_sigma_ep > 1) plnsx <- pops[[j]]$y else plnsx <- "sigma_ep"
    if(no_sigma_ep > 0){
      plt <- plot_parameters_areas(pops[[j]], 
                               paste0("sigma_ep[", 1:no_sigma_ep, "]"), 
                               plnsx, 
                               area_method = "equal height")
      tit <- "sigma_ep"
      if(length(pops) > 1) tit <- paste0(tit, ": Model ",j)
      plt <- plt + ggplot2::ggtitle(tit)
      suppressWarnings(print(plt))
    }
  cat("\n")
  }
}

```


```{r, echo=FALSE, results='asis', fig.height=4, fig.width=4,fig.show="hold", out.width="50%"}

if(!is.null(params$plot_parameters)){
  cat("## Additional parameter plots \n")
  for(j in seq_along(pops)){
    pn <- parameter_names(pops[[j]])
    cat("\n")
    for(i in seq_along(params$plot_parameters)){
      param_names <- names(params$plot_parameters)
      if(is.null(param_names)) param_names <- params$plot_parameters
      
      if(params$plot_parameters[i] %in% pn){
        plt <- plot_parameters_areas(pops[[j]], 
                                     params$plot_parameters[i], 
                                     params$plot_parameters[i], 
                                     area_method = "equal height")
        tit <- param_names[i]
        if(length(pops) > 1) tit <- paste0(tit, ": Model ",j)
        plt <- plt + ggplot2::ggtitle(tit)
        suppressWarnings(print(plt))  
      } else {
        cat("'", params$plot_parameters[i], "' does not exist in the model.", sep = "")
      }
    }
    cat("\n")
  }
}

```

```{r, results='asis', echo=FALSE}
if(!is.null(params$summary_parameters)){
  cat("## Parameter summary \n")
}
```
```{r, echo=FALSE}
if(!is.null(params$summary_parameters)){
  for(j in seq_along(pops)){
    pn <- parameter_names(pops[[j]])
    exist_params <- params$summary_parameters[which(params$summary_parameters %in% pn)]
    rstan:::print.stanfit(pop$stan_fit, pars = exist_params)
    if(!identical(exist_params, params$summary_parameters)){
      cat("\n\nNOTE! Some parameters was not found in the model.\n")
    }
  }
}
```


\pagebreak

# Model information

```{r, results='asis', echo=FALSE}
if(params$diagnostics_table){
  
  cat("## Model diagnostics\n")
  tab <- stanpop:::rmd_model_diagnostic_table(pops)
  n <- 5
  it <- ncol(tab)%/%n; rest <- ncol(tab)%%n
  if(rest > 0) it <- it + 1L
  for(i in 1:it){
    if(i == it) end <- ncol(tab) else end <- i*n
    ptab <- tab[,((i-1)*n + 1L):end, drop=FALSE]
    print(knitr::kable(ptab, 
                 digits = 1, 
                 caption = paste0("Model diagnostics ", i), 
                 row.names = TRUE))
  }

}
```


```{r,results='asis', echo=FALSE}

if(params$model_information){

  cat("\n## Model summary\n")
  knitr::kable(mi[order(mi$model), c("model", "sha", "model_setting", "polls_time_to")], 
               digits = 1, 
               caption = "Model summary", 
               row.names = FALSE)
  
}
```


```{r,results='asis', echo=FALSE}
if(params$model_information){
  rmd_print_model_information(pops)
}
```
